[workspace]
resolver = "3"
members = [
    "crates/archive-trait",
    "crates/tar-codec",
    "crates/tar-framing",
    "crates/tarpit",
    "crates/zip-framing",
    "crates/zip-codec",
]

[workspace.package]
edition = "2024"
homepage = "https://github.com/astral-sh/astral-codec"
repository = "https://github.com/astral-sh/astral-codec"
authors = ["William Woodruff <william@astral.sh>"]
license = "MIT OR Apache-2.0"
version = "0.0.14"

[workspace.dependencies]
archive-trait = { path = "crates/archive-trait", version = "0.0.14" }
tar-codec = { path = "crates/tar-codec", version = "0.0.14" }
tar-framing = { path = "crates/tar-framing", version = "0.0.14" }
zip-framing = { path = "crates/zip-framing", version = "0.0.14" }
zip-codec = { path = "crates/zip-codec", version = "0.0.14" }

async-compression = { version = "0.4", features = ["gzip", "tokio"] }
astral_async_zip = { version = "0.0.21", default-features = false, features = ["deflate", "tokio"] }
astral-tokio-tar = "0.7"
cap-std = "4.0.2"
clap = "4.6"
criterion = { package = "codspeed-criterion-compat", version = "=5.0.2", default-features = false, features = ["cargo_bench_support"] }
divan = { package = "codspeed-divan-compat", version = "5.0.2" }
flate2 = { version = "1.1.9", default-features = false, features = ["zlib-rs"] }
junction = "2.0.0"
tar = "0.4.46"
tempfile = "3"
thiserror = "2"
tokio = "1"
walkdir = "2.5.0"
windows-sys = { version = "0.60.2", features = ["Win32_Storage_FileSystem"] }
zip = { version = "8.6.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }

[workspace.lints.rust]
unsafe_code = "warn"
unreachable_pub = "warn"
