[package]
name = "zip-codec"
description = "Strict asynchronous ZIP decoding and encoding in safe Rust"
readme = "README.md"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
archive-trait = { workspace = true }
zip-framing = { workspace = true }
flate2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "rt"] }

[dev-dependencies]
astral_async_zip = { workspace = true }
divan = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt", "time"] }
zip = { workspace = true }

[[bench]]
name = "codec"
harness = false

[[bench]]
name = "comparison"
harness = false

[lints]
workspace = true
